version: 2
jobs:
  build:
    docker:
        - image: python:3.6.0
        
        
    working_directory: /tmp

    steps:
      - run:
          name: Creating Artifacts
          command: |
            echo "fragment-merge-plugin artifact file" > /tmp/artifacts;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts;

      - store_artifacts:
          path: /tmp/artifacts